---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalservices/docker-concourse-cf-tools 

inputs:
- name: source-repo

params:
  api_url:
  username:
  password:
  org:
  space:

run:
  path: /bin/bash
  args: 
    - source-repo/ci/tasks/build-test/task.sh
