groups:
- name: main
  jobs:
  - webhook-job
  - push_new
  - map-route
  - dummy

resources:
- name: source-repo
  type: git
  source:
    branch: master 
    uri: git@github.com:myminseok/concourse-demo-blug-green.git 
    private_key: {{github-private-key}}
  check_every: 6000s # for demo
  webhook_token: your_secure_random_webhooktoken

# https://concourse-ci.org/resources.html#resource-webhook-token
# to check resource:
# curl -k -X POST https://pcfdemo.net:9090/api/v1/teams/main/pipelines/demo-bg/resources/webhook-test/check/webhook\?webhook_token\=your_secure_random_webhooktoken -v
- name: timer 
  type: time
#  source: {interval: 99999h}
  source:
    start: 00:00 AM
    stop: 11:59 PM 
    location: Asia/Seoul
  webhook_token: your_secure_random_webhooktoken

- name: keyval
  type: keyval
  webhook_token: your_secure_random_webhooktoken
# curl -k -X POST https://pcfdemo.net:9090/api/v1/teams/main/pipelines/demo-bg/resources/version-repo/check/webhook\?webhook_token\=your_secure_random_webhooktoken -v
- name: version-repo 
  type: semver 
  source:
    driver: git
    uri: git@github.com:myminseok/concourse-demo-blug-green.git 
    branch: version
    file: version
    private_key: {{github-private-key}}
  webhook_token: your_secure_random_webhooktoken


jobs:
- name: dummy 
  plan: 
  - get: keyval
  - get: timer
  - do:
    - task: echo 
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: ubuntu
        run:
          path: sh
          args:
          - -exc
          - |
            echo "Hello $WORLD_PARAM"
      params:
        WORLD_PARAM: "hi"

- name: webhook-job
  plan: 
  - get: version-repo 
    trigger: true
  - do:
    - task: echo 
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: ubuntu
        run:
          path: sh
          args:
          - -exc
          - |
            echo "Hello $WORLD_PARAM"
      params:
        WORLD_PARAM: "hi"

- name: push_new
  plan:
  - get: source-repo
    trigger: true
  - task: push-new
    file: source-repo/ci/tasks/push-new/task.yml
    params:
      cf_api_url: {{cf_api_url}}
      cf_username: {{cf_username}}
      cf_password: {{cf_password}}
      cf_org: {{cf_org}}
      cf_space: {{cf_space}}
      cf_app_route: {{cf_app_route}}
      cf_domain: {{cf_domain}}

- name: map-route
  plan:
  - get: source-repo
    passed:
      - push_new
    trigger: false
  - task: map-route
    file: source-repo/ci/tasks/map-route/task.yml
    params:
      cf_api_url: {{cf_api_url}}
      cf_username: {{cf_username}}
      cf_password: {{cf_password}}
      cf_org: {{cf_org}}
      cf_space: {{cf_space}}
      cf_app_route: {{cf_app_route}}
